version: '3.9'

services:
  webserver:
    image: template-svelte-ts-docker-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
