name: Terraform

on: [push]

defaults:
  run:
    working-directory: infra

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TF_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.TF_KEY }}"
  
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform list
        run: terraform workspace list


      - name: Terraform select
        run: terraform workspace select ${{ secrets.TF_WORKSPACE }}

      - name: Terraform show
        run: terraform workspace select ${{ secrets.TF_WORKSPACE }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color